### ISSUE TITLE
Callback funciton doesn't work while use websocket client

### ISSUE THREAD

**Issue by xiaoyureed** [binance/binance-connector-python#116]
I'm trying to run example code in `examples/websocket/spot/all_book_ticker.py`

### Issue subject
No response print to console, it seems that function `message_handler` doesn't work.

### Expected behaviour
Response should be printed to console.

### Actual behaviour
No response print to console and No error occurred.

![image](https://user-images.githubusercontent.com/19821471/141675704-b698be54-899f-410b-a165-ce05be4bbab9.png)

### Steps to reproduce
run `all_book_ticker.py`

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python: v1.7.0
* Python version: Python 3.9.6
* Operating system: Macos big sure 11.6

**Comment by aisling11** [comment]
Hi @xiaoyureed, we can't reproduce this using the same environment as you (python 3.9.6 and python-connector v1.7.0), but this should not be related to `message_handler` because before the message handling, the log should contain successful ws connection info with `INFO binance.websocket.binance_client_protocol: Server connected`, which is not your case.

Can please confirm that there's no difference with:
a. the code in [all_book_ticker.py](https://github.com/binance/binance-connector-python/blob/master/examples/websocket/spot/all_book_ticker.py
)
b. the code in [binance_client_protocol.py](https://github.com/binance/binance-connector-python/blob/master/binance/websocket/binance_client_protocol.py)
c. the versions for the [required libraries](https://github.com/binance/binance-connector-python/blob/master/requirements/common.txt)

If it's all good above, can you also check if:
d.  Your code runs the `onConnect` method from [binance_client_protocol.py](https://github.com/binance/binance-connector-python/blob/master/binance/websocket/binance_client_protocol.py)
e. You're able to run without issue with previous [python-connector v1.6.0](https://pypi.org/project/binance-connector/1.6.0/)

Sorry for so many questions, although it will help us to gather more details and hopefully able to discover the issue.
